### ISSUE TITLE
Add benchmarks against other tar implementions in js and other languages

### ISSUE THREAD

**Issue by johnpyp** [unjs/nanotar#8]
### Describe the change

nanotar is described as "fast", but it's unclear in comparison to what. I've used node-tar in the past, and was amazed by how *slow* it was compared to other implementations in other languages. Is nanotar faster? Can't tell :)

### URLs

N/A

### Additional information

- [ ] Would you be willing to help?

**Comment by pi0** [comment]
it is a tiny lib that specifictly works with tar format not fs stuff and up to you how to use it. It is fast by itself not comparable to "other" implementations.
